### ISSUE TITLE
How to store fit parameters?

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/GAS#11]
I was wondering what is the best option to store the best fit parameters. Currently, PropertyMaps.py creates a single FITS file with each plane representing one best fit parameter or its associated uncertainty. Should it be better to store each parameter in a different HDU within the FITS file? This is similar to the Herschel data format. In this way, we can change the BUNIT keyword to represent the real unit of the fit parameter.

One clear disadvantage is that casaviewer does not work really well with it. In ds9 or casaviewer we can just change the channel to see the different parameters. What are your thoughts @low-sky @rfriesen ?

We should think about the impact on other team members... i.e. how easy would it be for them to understand and/or access the results.?

**Comment by jpinedaf** [comment]
I created a conversion function (see #44) between the current line fit output (every parameter is stored in a single channel of a cube) and one where each parameter is stored into a single image within a hdu list. 

This is the first step, and I'm planning on editing the remaining functions to ensure that they store/use the results with this new format. If you have suggestions, this is the right time to voice them :)

**Comment by low-sky** [comment]
I'd lean toward one file per parameter, but I'm okay with one HDU per parameter too.  Better than a cube, for sure.  I see good things with multi-HDU files being that everything is in one place and versioning is easier.

**Comment by jpinedaf** [comment]
It is as easy to make one file per parameter, as it is to make a multi-HDU
file. I see the problem of opening multi-HDU files in CASA as a good reason
to go with the former option.

**Comment by jpinedaf** [comment]
any comments @rfriesen ? It looks like creating one file for each parameter might be the less problematic.

**Comment by rfriesen** [comment]
I like the tidiness of having one HDU per parameter, but I think it 
might make life easier for other people to have individual files per 
parameter. A lot of people are still using IDL, too - how does it handle 
multiple HDUs in a fits file? As Erik suggested in the workshop - we can 
do both? The parameter files aren't all that large.

**Comment by jpinedaf** [comment]
I noticed that the current/old method of storing the data is useful to use the viewer in pyspeckit, while there is already a function to transform to the future/new method which creates the different FITS files for each parameter. I think it might be a good compromise to keep them both :)

**Comment by jpinedaf** [comment]
This is now working. We are actually keeping both options since, as discussed, we could explore the fits by loading the fits cube into `pyspeckit`
