### ISSUE TITLE
How to best mask property maps for DR1 release

### ISSUE THREAD

**Issue by rfriesen** [GBTAmmoniaSurvey/GAS#147]
In a previous telecon, we discussed masking the Tk, N(NH3) property maps based on S/N > 3 in the (2,2) line. This gives a very conservative result, with regions masked where the properties still seem to vary smoothly and have relatively low uncertainty in the fitted parameters (e.g. <1-2 K for Tk). 

In the current cold_ammonia model, can Tk be constrained relatively well even when the S/N in the (2,2) line is low (or the (2,2) line is undetected)? @keflavich @low-sky @jpinedaf

**Comment by keflavich** [comment]
Statistically good fits can be achieved with low S/N in the (2,2) line, but they are likely to be hiding large degeneracies in which a range of temperatures lower than the best-fit temperature are acceptable.  It would probably be best to examine a few example spectra+fits directly and see.  If the values are varying smoothly, we have some 'prior information' that the temperatures really are close to the neighboring pixels' value, and perhaps we can allow lower s/n if the temperatures are close to the local mean of high s/n neighbors.

**Comment by rfriesen** [comment]
That makes sense, thanks. On closer inspection part of the issue was due to calculating S/N based on the integrated (2,2) intensity - if I use the line peak instead, a lot of the smoothly-varying Tkin pixels are actually above the S/N threshold.
