### ISSUE TITLE
Need to switch to release version of gbtpipeline in gasPipeline

### ISSUE THREAD

**Issue by rfriesen** [GBTAmmoniaSurvey/GAS#152]
Per Joe Masters:

The release version of the pipeline (gbtpipeline) was updated today to version 1.3.  If necessary, you can still access the previous release (1.2) with gbtpipeline-old.

I suggest you switch to the release version if you are currently using gbtpipeline-test, as it will be more stable for future use.  The test version will change on occasion, so you can still look to gbtpipeline-test for bug fixes before they appear in a release.

**Comment by jpinedaf** [comment]
I think this has been addressed already
