### ISSUE TITLE
Fit properties returned with zero error where parameter hits minimum in cubefit

### ISSUE THREAD

**Issue by rfriesen** [GBTAmmoniaSurvey/GAS#50]
In some pixels, cubefit returns fit properties with zero error where that particular parameter has hit the minimum limit in the cubes.fiteach call. I see this mostly in the Tkin maps, where a pixel shows Tkin = 5.0 with eTkin = 0.0. We can flag this out in later steps but I think it makes more sense to return zero for a parameter value when the error is zero.

**Comment by jpinedaf** [comment]
I think that is the expected behavior, I saw the same with mpfit in IDL.
This should be part of the flagging or masking for the second fit
