### ISSUE TITLE
Adding date to pipeline wrapper

### ISSUE THREAD

**Issue by rfriesen** [GBTAmmoniaSurvey/GAS#59]
Hey @low-sky @jpinedaf , 

Is there an easy way to add a date to the pipeline wrapper? This would be useful when we change the gain parameters but don't want to re-reduce *all* the survey data. 

I can look into this in a couple days but thought I'd ask in case there's a simple solution!

r.

**Comment by low-sky** [comment]
Sure.  Dates are easy enough, but to be clear, what sort of functionality does this need to show?  Do you want the date of processing to be in the FITS file outputs?  Or are you asking for the ability to just run the pipeline for a range of dates in the raw files?  The latter seems more consistent with the intent of your question.

**Comment by rfriesen** [comment]
Yep, running the pipeline for a range of dates, when we don't want to re-reduce, e.g., 15A data but do want to re-reduce 15B.

**Comment by jpinedaf** [comment]
I guess it could be adding an extra comparison point in https://github.com/GBTAmmoniaSurvey/GAS/blob/master/GAS/gasPipeline.py#L47
like 
```
if (region == observation['Region name']) & (date == observation['Date']):
```
and add a new parameter to the `wrapper` function

**Comment by low-sky** [comment]
I was looking in a little more detail here.  I think we want to reformat the date into `datetime.date` objects so we can do things like 
```
(observation_date > startdate) & (observation_date < enddate)
```
I was bogged down in trying to coax google sheets into reformatting the date into [ISO 8601](https://xkcd.com/1179/) ordering.

**Comment by jpinedaf** [comment]
It works nicely! We just need to member that the dates are not inclusive.
