### ISSUE TITLE
Sub-package for GAS DR1

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/GAS#65]
Thanks to the flexibility in the data reduction and gridding pipeline (see #63 and #61) we could create a sub-package for the sole purpose of producing the **GAS Data Release 1**. This should produce a an end-to-end processing of the data and use a file extension like `_DR1.fits`

This should be a fairly minimal effort, because most (if not all) of the functions are already defined and working in the `run_grid_regions` sub-package (https://github.com/GBTAmmoniaSurvey/GAS/blob/master/GAS/run_grid_regions.py).

I'll work on this in the next few days, so if you have any suggestions/opinions this is the right moment to voice them :) @low-sky @rfriesen  @keflavich

**Comment by low-sky** [comment]
I think this is a good time to try this :+1:.
We can also tag for DR2, which would include the more value added components.  It would be useful to write down what the DR1 products will be.

**Comment by jpinedaf** [comment]
Sure, a DR2 tag also makes sense. 
DR1 products are: 
-baseline subtracted cubes
-integrated intensity maps
-line fit outputs

 We need to make a list of the regions to be produced for DR1 and the sessions to use, e.g. should we include only observations from previous the semester? In the case of L1688 the new data gets a much nicer map. Maybe we could release all regions that have been completed: NGC1333, Oph, OrionA-North, and B18.

I think that it would be great to include the improved integrated intensity calculation (using the centroid velocity from the line-fit), only if this can be done in a short period of time.

Clearly we will have to discuss this in the next (or future) telecon, but it would be useful to know what we think can be done in a short period of time.

Also, once we identify "milestones" and "tasks,"  is there a preferred way to keep track of them in GitHub?

**Comment by low-sky** [comment]
What date do we want a DR1 by?

**Comment by jpinedaf** [comment]
Tomorrow? ;) It would be great to show the real data at the AAS, and then
have time to write the papers in the following months. However, I see that
it could be a bit too rushed to have something in the next weeks, so I
would suggest an internal delivery date of 15-Feb-2016, what do you think?

On Mon, Dec 7, 2015 at 2:27 PM Erik Rosolowsky <notifications@github.com>
wrote:

> What date do we want a DR1 by?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GBTAmmoniaSurvey/GAS/issues/65#issuecomment-162523962>
> .
>
-- 
------------------------------
Dr. Jaime E Pineda                  Phone: +49 89 300003610
Max-Planck-Institut für extraterrestrische Physik
Giessenbachstrasse 1
85748 Garching
Germany

**Comment by keflavich** [comment]
@jpinedaf why a "sub-package"?  Could you just tag the current code as "dr1" and "release" it?

**Comment by low-sky** [comment]
This seems like a different case in that @jpinedaf also needs code specific to the DR.  As methods improve, that code might also change. It would be nice to create. Dr1 module that will always be in the code and able to produce the DR1 data.  Presumably, there would be a tag and release for the code concurrent with that.

**Comment by low-sky** [comment]
Thinking further (catching up with @keflavich ) you could just do a release module and then have the tagged version of the software match up with the the DR.  It seems more git like to do this, but I'm not sure of which is nicer aesthetically.  I guess if you want to produce DR1 and DR2 from the same code you would have to do different code for each in the same version.

**Comment by jpinedaf** [comment]
I see what you are saying @keflavich @low-sky . One of the big differences would be that for OrionA-North we would like to include a subset of the sessions and probably give them a different extension. At the same time, we would like to keep imaging the DR1 footprints and the new ones to see the progress. Since all the data will be available at the end, we also would like to have the option of creating the DR1 and DR2 products to ensure reproducibility of the results.

@low-sky what do you mean by **release module**? I'm really new to git, so this is beyond my comfort zone... happy to learn from the more experienced :)

Maybe an alternative would be to generate a DR1 keyword for the gridding and firstlook functions for the regions to be released that defines the sessions to be used and the file extension. In this way we can keep the same code structure.

**Comment by keflavich** [comment]
@jpinedaf to make a `tag`, you just do `git tag <tagname>`, e.g. `git tag DR`.  Then, push those to the repository with `git push --tags`.  You can then go to the 'releases'  zone (e.g., https://github.com/GBTAmmoniaSurvey/GAS/releases) and turn a tag into a 'release' with notes.

**Comment by low-sky** [comment]
I'm converging on the idea of making a submodule/directory in the main code called `releases`.  In releases would be databases (errr, text files) indicating what goes into a DR plus the driver code that can run a release end-to-end from pipeline to FITS on disk for all the relevant regions.  Thus, initially, it would contain one code file `dr1.py` and any ancillary data.  Thus, you get something like this.

"""
import GAS.releases.dr1 as dr1
dr1.MakeRelease(OutputDirectory='/home/maxpowers/GAS/DR1/')
"""

The main routines in GAS should be refined / separated to produce the different steps in the pipeline.  In particular, I agree that code for a second pass through generating moments is still needed.  The code would then be tagged as v1.0.  

As for management, I use github to record issues and assign them to people and to milestones.  The issues can have checklists like so.

Moment generation code:

- [ ] Mask generation code using fit results
- [ ] Generate moments from masks
- [ ] Uncertainty code in moments.

**Comment by keflavich** [comment]
@low-sky check out #66 and see if it looks OK to you.  You can't import GAS then run a GAS release, as you suggested, because we want the script to install a specific version of GAS.  That's the only caveat, I think.

**Comment by jpinedaf** [comment]
I'll close this issue, the details for the individual tasks to complete DR1 will be created as individual issues
