### ISSUE TITLE
should we remove edges?

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/GAS#76]
Should we remove the edge of the maps? which are very noisy even in the integrated intensity map. 

I would do it as an erosion of all cubes with a `disk(1)` or `disk(2)` after baselining the cube. What do you think? @low-sky @rfriesen

**Comment by jpinedaf** [comment]
This is a quick comparison between the original image, and two possible edge trimming procedures
```python
import numpy as np
from skimage.morphology import disk,dilation
# create initial mask
# and remove the edges, which don't disappear by default
mask=np.isnan(TdV)
mask[:,0]=True
mask[:,-1]=True
mask[0,:]=True
mask[-1,:]=True
#plot tests
plt.imshow(TdV, origin='lower',interpolation='nearest',vmin=-0.5, vmax=3.)
plt.imshow(TdV*(1-dilation(mask,disk(2))), origin='lower',interpolation='nearest',vmin=-0.5, vmax=3.)
plt.imshow(TdV*(1-dilation(mask,disk(3))), origin='lower',interpolation='nearest',vmin=-0.5, vmax=3.)
```
![l1688_withedge](https://cloud.githubusercontent.com/assets/6529114/11867109/59d28e64-a4af-11e5-8b19-887eae67c8d7.png)
![l1688_noedge_disk2](https://cloud.githubusercontent.com/assets/6529114/11867110/59d2c5e6-a4af-11e5-8c61-806ffe95e72b.png)
![l1688_noedge_disk3](https://cloud.githubusercontent.com/assets/6529114/11867111/59d3329c-a4af-11e5-9139-b71911e5f5d6.png)

**Comment by rfriesen** [comment]
I've got a moment map flagging written in to the PropertyMaps code (flag_all_data), but it is simply making a cut in the rms map (the default is 0.2 K). Your edge masking looks more smooth - are you just trimming x pixels in from the edge?

**Comment by low-sky** [comment]
All these approaches should be roughly equivalent.  The noise clip approach will retain the most data but the edge erosion will be the tidiest.  Given there's probably nothing we should focus on at the edges, I think that the erosion is probably the best approach.

**Comment by jpinedaf** [comment]
I was thinking on removing all those pixels also in the cubes, so if anybody else downloads the data, then they would not see this issue. I assume this is OK, given the comments above, unless someone really wants to do it only in the data products and not in the data

My vote is for using `disk(3)` (bottom panel above) for the erosion, if anybody prefers `disk(2)` (middle panel above) just let me know

**Comment by rfriesen** [comment]
Looks good to me. For some of the newer footprints in Orion AS and Serpens,
the edges are quite a bit noisier, but since those aren't part of DR1 we
can figure out what to do about them later.

**Comment by jpinedaf** [comment]
done
