### ISSUE TITLE
function to determine if scans are associated with a DR

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/GAS#95]
@low-sky 

- [x] -create a column in the observing log with the info if using scan for DR or not.
- [x] -create function within the pipeline to parse this information to create the list of files in the gridder

**Comment by jpinedaf** [comment]
I noticed that @low-sky already created the column in the observing log. I updated the values to make sure we include the right scans for Oph in DR1, everything else should include only the observations until the end of the first semester.

**Comment by low-sky** [comment]
Yup.  I'm slowly ploughing through the code needed to support this... but we have turbulence code working instead.

**Comment by low-sky** [comment]
@jpinedaf -- This should be in part in #114 
Is there additional functionality that needs to be brought in?

**Comment by low-sky** [comment]
Up and running a long time ago.
