### ISSUE TITLE
store a DR1 observing log

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/GAS#96]
@keflavich We want to include the Observing log to be used in DR1. Then we don't need to download, but to deploy from the already installed pipeline. You mentioned that there is a proper way to do it, with some examples from the astropy test suite... any pointers?

**Comment by keflavich** [comment]
This is an example from astroquery:

https://github.com/astropy/astroquery/blob/master/astroquery/alma/tests/setup_package.py

This code works with something in astropy-helpers: http://docs.astropy.org/en/stable/development/building.html#customizing-setup-build-for-subpackages

**Comment by low-sky** [comment]
Addressed in #103
