### ISSUE TITLE
Ungraceful fitting exit

### ISSUE THREAD

**Issue by low-sky** [GBTAmmoniaSurvey/GAS#97]
I'm getting a segfault when the fitting finishes.  

```
The use of header.update() to add new keywords to a header is deprecated.  Instead, use either header.set() or simply `header[keyword] = value` or `header[keyword] = (value, comment)`.  header.set() is only necessary to use if you also want to use the before/after keyword arguments.

In [2]: /Users/erik/anaconda/bin/python.app: line 3:  1329 Segmentation fault: 11  /Users/erik/anaconda/python.app/Contents/MacOS/python "$@"
```
It's not clear if the two issues are related.  Fortunately, the results write out before the crash.

**Comment by keflavich** [comment]
These are probably not related.  I've seen segfaults like that before but never managed to understand them.  The header update warning is something that should be fixed, but I'm not sure where exactly it is.

**Comment by low-sky** [comment]
Not happening anymore?
